import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { Article } from "@/components/sections-components/Article";
import {
  BLOGS_PATH,
  getContentBySlug,
  getContentSlugs,
  PROJECTS_PATH,
} from "@/lib/content";

const EYEBROW = {
  work: "case study",
  blog: "blog entry",
} as const;

interface PageProps {
  params: Promise<{ section: "work" | "blog"; slug: string }>;
}

// Tells Next.js all route params have be generated, there will be no dynamic
// endpoints. If it finds a param not generated by `generateStaticParams` then
// return 404
export const dynamicParams = false;

// Create all static URLs
export function generateStaticParams() {
  const projects = getContentSlugs(PROJECTS_PATH).map((slug) => ({
    section: "work",
    slug,
  }));
  const blogs = getContentSlugs(BLOGS_PATH).map((slug) => ({
    section: "blog",
    slug,
  }));

  return [...projects, ...blogs];
}

// Dynamic Metadata for both:
export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { section, slug } = await params;
  const contentPath = section === "work" ? PROJECTS_PATH : BLOGS_PATH;
  const item = getContentBySlug(contentPath, slug);

  if (!item) return {};

  return {
    title: item.title,
    description: item.summary,
    alternates: { canonical: `/${section}/${item.slug}` },
    openGraph: {
      title: item.title,
      description: item.summary,
      type: "article",
      url: `/${section}/${item.slug}`,
      images: item.summaryImage?.src ? [item.summaryImage.src] : undefined,
    },
    twitter: {
      card: "summary_large_image",
      title: item.title,
      description: item.summary,
      images: item.summaryImage?.src ? [item.summaryImage.src] : undefined,
    },
  };
}

export default async function ContentPage({ params }: PageProps) {
  const { section, slug } = await params;
  const contentPath = section === "work" ? PROJECTS_PATH : BLOGS_PATH;
  const item = getContentBySlug(contentPath, slug);

  if (!item) notFound();

  return (
    <Article
      content={item}
      eyebrow={EYEBROW[section]}
    />
  );
}
